import { PermissionsBitField, EmbedBuilder, ActionRowBuilder, ModalBuilder, TextInputBuilder, ChannelType } from 'discord.js';
import { randomInt } from 'node:crypto';
import { appendFile, writeFile } from 'node:fs/promises';
import { db, transaction, log, safeFile } from './store.mjs';
import { transform, regex, http, file, sql, external } from './utils.mjs';
import { system } from './systems.mjs';
import { integration } from './integrations.mjs';
export async function channel(ctx,id){const value=String(id||ctx.channel?.id||'').replace(/[<#>]/g,'');if(!value)throw Error('Не указан канал');const c=await ctx.services.client.channels.fetch(value);if(!c)throw Error('Канал не найден');return c;}
export async function member(ctx,id){if(!ctx.guild?.id)throw Error('Действие доступно только на сервере');const g=await ctx.services.client.guilds.fetch(ctx.guild.id);return g.members.fetch(String(id||ctx.user?.id||'').replace(/[<@!>]/g,''));}
export async function send(ctx,payload,mode='reply',targetChannel,targetUser){const i=ctx.interaction;payload={allowedMentions:{parse:[]},...payload};if(mode==='dm'){const u=await ctx.services.client.users.fetch(String(targetUser||ctx.user?.id));return u.send(payload);}if(mode==='reply'&&i){if(i.deferred&&!ctx.replied){ctx.replied=true;const {flags,...rest}=payload;return i.editReply(rest);}if(i.replied||ctx.replied)return i.followUp(payload);ctx.replied=true;return i.reply({...payload,fetchReply:true});}if(mode==='reply'&&ctx.message)return ctx.message.reply(payload);return (await channel(ctx,targetChannel)).send(payload);}
function compare(a,b,op){switch(op){case 'equals':return JSON.stringify(a)===JSON.stringify(b)||String(a)===String(b);case 'not_equals':return !(JSON.stringify(a)===JSON.stringify(b)||String(a)===String(b));case 'greater':return Number(a)>Number(b);case 'less':return Number(a)<Number(b);case 'gte':return Number(a)>=Number(b);case 'lte':return Number(a)<=Number(b);case 'contains':return Array.isArray(a)?a.includes(b):String(a??'').includes(String(b));case 'starts':return String(a??'').startsWith(String(b));case 'ends':return String(a??'').endsWith(String(b));default:throw Error('Неизвестный оператор');}}
const bool=v=>!(v===false||v==='false'||v===0||v==='0'||v==null||v==='');
export async function action(kind,p,ctx){
 if(kind.startsWith('system.'))return system(kind,p,ctx);
 if(['socket.connect','socket.send','socket.close','network.send','webhook.listen','voice.control'].includes(kind))return integration(kind,p,ctx);
 switch(kind){
 case 'condition.compare':return compare(p.left,p.right,p.operator);
 case 'condition.chance':return Math.random()*100<Math.max(0,Math.min(100,p.percent));
 case 'condition.logic':{if(!Array.isArray(p.values))throw Error('Ожидается массив значений');return p.operator==='AND'?p.values.every(bool):p.operator==='OR'?p.values.some(bool):!bool(p.values[0]);}
 case 'condition.access':return p.mode==='whitelist'?p.ids.map(String).includes(String(p.value)):!p.ids.map(String).includes(String(p.value));
 case 'condition.cooldown':return transaction(()=>{const row=db.prepare('SELECT until FROM cooldowns WHERE project=? AND key=?').get(ctx.project.id,p.key);if(row?.until>Date.now())return false;db.prepare('INSERT OR REPLACE INTO cooldowns VALUES(?,?,?)').run(ctx.project.id,p.key,Date.now()+Math.max(0,p.seconds)*1000);return true;});
 case 'condition.member':{const m=await member(ctx,p.user);switch(p.check){case 'role':return m.roles.cache.has(String(p.value));case 'any_role':return String(p.value).split(',').some(id=>m.roles.cache.has(id.trim()));case 'permission':return m.permissions.has(p.value);case 'id':return m.id===String(p.value);case 'bot':return m.user.bot===bool(p.value||true);case 'status':return (m.presence?.status||'offline')===p.value;}return false;}
 case 'condition.channel':{const c=await channel(ctx);return p.check==='id'?c.id===String(p.value):p.check==='category'?c.parentId===String(p.value):Boolean(c.nsfw);}
 case 'message.send':{const payload={};if(p.content)payload.content=String(p.content);if(p.embeds?.length)payload.embeds=p.embeds.map(e=>new EmbedBuilder(e));if(p.components?.length)payload.components=p.components;if(p.files?.length)payload.files=p.files.map(f=>safeFile(ctx.project.id,typeof f==='string'?f:f.path));if(p.poll)payload.poll=p.poll;if(p.ephemeral&&ctx.interaction)payload.flags=64;const m=await send(ctx,payload,p.mode,p.channel,p.user);return {id:m.id,channelId:m.channelId,content:m.content};}
 case 'message.random':{if(!Array.isArray(p.messages)||!p.messages.length)throw Error('Добавьте варианты ответа');const m=await send(ctx,{content:String(p.messages[randomInt(p.messages.length)])});return {id:m.id,content:m.content};}
 case 'message.manage':{const c=await channel(ctx,p.channel);if(!c.messages)throw Error('В канале нет сообщений');const m=await c.messages.fetch(String(p.message||ctx.message?.id));switch(p.action){case 'edit':await m.edit({content:String(p.content),allowedMentions:{parse:[]}});break;case 'delete':await m.delete();break;case 'pin':await m.pin();break;case 'unpin':await m.unpin();break;case 'publish':await m.crosspost();break;case 'react':await m.react(p.emoji);break;case 'unreact':{const r=m.reactions.cache.find(r=>r.emoji.id===p.emoji||r.emoji.name===p.emoji);if(r)await r.users.remove(ctx.services.client.user.id);break;}}return {id:m.id};}
 case 'message.purge':{const c=await channel(ctx,p.channel);if(!c.bulkDelete)throw Error('Канал не поддерживает массовое удаление');const messages=await c.messages.fetch({limit:Math.max(1,Math.min(100,p.count))});const filtered=p.user?messages.filter(m=>m.author.id===String(p.user)):messages;return {deleted:(await c.bulkDelete(filtered,true)).size};}
 case 'component.modal':{const i=ctx.interaction;if(!i?.showModal||i.deferred||i.replied)throw Error('Форму нужно открыть первым действием interaction');const modal=new ModalBuilder().setCustomId(p.customId).setTitle(p.title);for(const f of p.fields.slice(0,5)){const field=new TextInputBuilder().setCustomId(f.id).setLabel(f.label).setStyle(f.style||1).setRequired(f.required??true);if(f.placeholder)field.setPlaceholder(f.placeholder);if(f.value)field.setValue(f.value);modal.addComponents(new ActionRowBuilder().addComponents(field));}await i.showModal(modal);ctx.replied=true;return true;}
 case 'component.autocomplete':if(!ctx.interaction?.isAutocomplete())throw Error('Это не autocomplete');await ctx.interaction.respond(p.choices.slice(0,25));return true;
 case 'component.defer':{const i=ctx.interaction;if(i&&!i.deferred&&!i.replied)await i.deferReply(p.ephemeral?{flags:64}:{});return true;}
 case 'member.moderate':{const g=await ctx.services.client.guilds.fetch(ctx.guild.id);if(p.action==='unban'){await g.members.unban(p.user,p.reason);return true;}if(p.action==='warn'){const id=crypto.randomUUID();db.prepare('INSERT INTO warnings VALUES(?,?,?,?,?,?)').run(id,ctx.project.id,g.id,String(p.user),p.reason,Date.now());return {id,count:db.prepare('SELECT COUNT(*) AS n FROM warnings WHERE project=? AND guild=? AND user=?').get(ctx.project.id,g.id,String(p.user)).n};}if(p.action==='warnings')return db.prepare('SELECT id,reason,created FROM warnings WHERE project=? AND guild=? AND user=?').all(ctx.project.id,g.id,String(p.user));const m=await member(ctx,p.user);if(p.action==='kick')await m.kick(p.reason);if(p.action==='ban')await m.ban({reason:p.reason});if(p.action==='timeout')await m.timeout(Math.max(0,Math.min(40320,p.minutes))*60000,p.reason);if(p.action==='untimeout')await m.timeout(null,p.reason);return {id:m.id};}
 case 'role.manage':{const g=await ctx.services.client.guilds.fetch(ctx.guild.id);if(['add','remove'].includes(p.action)){const m=await member(ctx,p.user);await m.roles[p.action](String(p.role).split(',').map(s=>s.trim()).filter(Boolean),p.reason);return {user:m.id};}const data={...p.data,reason:p.reason};if(data.permissions) data.permissions=new PermissionsBitField(data.permissions);if(p.action==='create'){const r=await g.roles.create(data);return {id:r.id,name:r.name};}const role=await g.roles.fetch(p.role);if(!role)throw Error('Роль не найдена');if(p.action==='delete')await role.delete(p.reason);else await role.edit(data);return {id:role.id,name:role.name};}
 case 'channel.manage':{const g=await ctx.services.client.guilds.fetch(ctx.guild.id);if(p.action==='create'){const c=await g.channels.create({...p.data,reason:p.reason});return {id:c.id,name:c.name};}const c=await channel(ctx,p.channel);if(p.action==='thread_create'){if(!c.threads)throw Error('В этом канале нельзя создать ветку');const thread=await c.threads.create({...p.data,reason:p.reason});return {id:thread.id,name:thread.name};}if(['delete','thread_delete'].includes(p.action))await c.delete(p.reason);else await c.edit({...p.data,reason:p.reason});return {id:c.id,name:c.name};}
 case 'member.voice':{const m=await member(ctx,p.user);switch(p.action){case 'move':await m.voice.setChannel(p.channel,p.reason);break;case 'disconnect':await m.voice.disconnect(p.reason);break;case 'mute':case 'unmute':await m.voice.setMute(p.action==='mute',p.reason);break;case 'deafen':case 'undeafen':await m.voice.setDeaf(p.action==='deafen',p.reason);break;}return true;}
 case 'data.user':{const client=ctx.services.client;const id=p.id||ctx.user?.id;if(p.entity.startsWith('mention_'))return p.entity==='mention_user'?`<@${id}>`:p.entity==='mention_role'?`<@&${p.id}>`:`<#${p.id||ctx.channel?.id}>`;if(p.entity==='bot')return {id:client.user.id,username:client.user.username,avatar:client.user.displayAvatarURL(),ping:client.ws.ping,uptime:client.uptime};if(p.entity==='user'){const u=await client.users.fetch(id);return {id:u.id,username:u.username,tag:u.tag,bot:u.bot,avatar:u.displayAvatarURL(),createdAt:u.createdAt.toISOString()};}if(p.entity==='member'){const m=await member(ctx,id);return {id:m.id,name:m.displayName,joinedAt:m.joinedAt?.toISOString(),roles:[...m.roles.cache.keys()],status:m.presence?.status||'offline'};}if(p.entity==='channel'){const c=await channel(ctx,p.id);return {id:c.id,name:c.name,type:c.type,position:c.position,parentId:c.parentId};}const g=await client.guilds.fetch(p.entity==='guild'?(p.id||ctx.guild.id):ctx.guild.id);if(p.entity==='guild')return {id:g.id,name:g.name,memberCount:g.memberCount,ownerId:g.ownerId,boosts:g.premiumSubscriptionCount,level:g.premiumTier};const r=await g.roles.fetch(p.id);if(!r)throw Error('Роль не найдена');return {id:r.id,name:r.name,color:r.hexColor,permissions:r.permissions.toArray(),position:r.position};}
 case 'data.transform':return transform(p);case 'data.regex':return regex(p);case 'data.file':return file(p,ctx);case 'data.sql':return sql(p,ctx);case 'data.external':return external(p);case 'http.request':return http(p,ctx.run.controller.signal);
 case 'image.render':{const {default:sharp}=await import('sharp');const width=Math.max(1,Math.min(4096,p.width)),height=Math.max(1,Math.min(4096,p.height));const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));const svg=`<svg width="${width}" height="${height}">${p.lines.map(l=>`<text x="${Number(l.x)||0}" y="${Number(l.y)||0}" font-family="Arial" font-size="${Math.min(300,Number(l.size)||32)}" fill="${escape(l.color||'#fff')}">${escape(l.text)}</text>`).join('')}</svg>`;const base=p.image?sharp(safeFile(ctx.project.id,p.image)).resize(width,height,{fit:'cover'}):sharp({create:{width,height,channels:4,background:p.background}});await base.composite([{input:Buffer.from(svg)}]).png().toFile(safeFile(ctx.project.id,p.file));return {file:p.file};}
 case 'service.log':{const text=typeof p.message==='string'?p.message:JSON.stringify(p.message);log(ctx.project.id,p.level,text);if(p.file)await appendFile(safeFile(ctx.project.id,'bot.log'),`${new Date().toISOString()} ${p.level}: ${text}\n`);if(p.channel)await send(ctx,{content:text.slice(0,1900)},'channel',p.channel);return true;}
 case 'service.assert':if(!bool(p.value))throw Error(p.message);return true;
 case 'service.export':{const value=typeof p.value==='string'?JSON.parse(p.value):p.value;let content;if(p.format==='csv'){if(!Array.isArray(value))throw Error('Для CSV нужен массив объектов');const keys=[...new Set(value.flatMap(v=>Object.keys(v)))];const quote=v=>'"'+String(v??'').replaceAll('"','""')+'"';content=[keys.map(quote).join(','),...value.map(row=>keys.map(k=>quote(typeof row[k]==='object'?JSON.stringify(row[k]):row[k])).join(','))].join('\r\n');}else content=JSON.stringify(value,null,2);const name=`${p.file}.${p.format}`;await writeFile(safeFile(ctx.project.id,name),content);return {file:name};}
 default:throw Error(`Нет обработчика ${kind}`);
 }
}
