import { Client, GatewayIntentBits, Partials, REST, Routes, PermissionsBitField, AuditLogEvent } from 'discord.js';
import { CronExpressionParser } from 'cron-parser';
import { db, getProject, validateProject, log } from './store.mjs';
import { startRun, runs, cancelRun } from './engine.mjs';
import { cleanup } from './integrations.mjs';
import { finishGiveaway } from './systems.mjs';
export const bots=new Map();
const events={guildMemberAdd:'member_join',guildMemberRemove:'member_leave',guildMemberUpdate:'member_update',guildBanAdd:'member_ban',guildBanRemove:'member_unban',channelCreate:'channel_create',channelDelete:'channel_delete',channelUpdate:'channel_update',roleCreate:'role_create',roleDelete:'role_delete',roleUpdate:'role_update',messageUpdate:'message_update',messageDelete:'message_delete',messageReactionAdd:'reaction_add',messageReactionRemove:'reaction_remove',voiceStateUpdate:'voice_update',presenceUpdate:'presence_update',inviteCreate:'invite_create',inviteDelete:'invite_delete',emojiCreate:'emoji_create',emojiDelete:'emoji_delete',emojiUpdate:'emoji_update',stickerCreate:'sticker_create',stickerDelete:'sticker_delete',stickerUpdate:'sticker_update',threadCreate:'thread_create',threadDelete:'thread_delete',threadUpdate:'thread_update',guildScheduledEventCreate:'scheduled_event_create',guildScheduledEventUpdate:'scheduled_event_update',guildScheduledEventDelete:'scheduled_event_delete',guildScheduledEventUserAdd:'scheduled_event_user_add',guildScheduledEventUserRemove:'scheduled_event_user_remove',stageInstanceCreate:'stage_create',stageInstanceDelete:'stage_delete',stageInstanceUpdate:'stage_update',autoModerationActionExecution:'automod_action',guildUpdate:'guild_update'};
function userData(u){return u?{id:u.id,username:u.username,tag:u.tag,bot:u.bot,avatar:u.displayAvatarURL?.()}:undefined;}
function base(value){const message=value?.message||(value?.author?value:null);const guild=value?.guild||message?.guild;const channel=value?.channel||message?.channel||(value?.isTextBased?value:null);const user=value?.user||value?.author||value?.member?.user||message?.author;return {guild:guild?{id:guild.id,name:guild.name,memberCount:guild.memberCount,locale:guild.preferredLocale}:undefined,channel:channel?{id:channel.id,name:channel.name}:undefined,user:userData(user),content:message?.content,message,locale:guild?.preferredLocale||'ru',event:{id:value?.id}};}
export function botState(id){const b=bots.get(id);if(!b)return {status:'offline',guilds:0,ping:0,uptime:0};return {status:b.status,error:b.lastError,username:b.client.user?.tag,avatar:b.client.user?.displayAvatarURL(),guilds:b.client.guilds.cache.size,ping:b.client.ws.ping,uptime:b.client.uptime||0,runs:[...runs.values()].filter(r=>r.project===id).length};}
function trigger(s){return s.nodes.find(n=>n.data?.kind?.startsWith('trigger.'));}
function launch(b,s,input){const active=[...runs.values()].filter(r=>r.project===b.project.id&&['running','paused'].includes(r.status)).length;if(active>=30){log(b.project.id,'warning','Событие пропущено: уже выполняются 30 сценариев');return;}const id=startRun(b.project,s,input,b.services);return runs.get(id);}
function dispatch(b,event,input={}){for(const s of b.project.scenarios){if(s.enabled===false)continue;const t=trigger(s);if(t?.data.kind==='trigger.event'&&t.data.params.event===event&&(!t.data.params.channel||t.data.params.channel===input.channel?.id))launch(b,s,{...input,event:{...input.event,type:event}});}}
function schedule(b){
 b.schedules=[];for(const s of b.project.scenarios){if(s.enabled===false)continue;const t=trigger(s);if(t?.data.kind!=='trigger.schedule')continue;const p=t.data.params;const expression=p.mode==='cron'?CronExpressionParser.parse(p.cron,{tz:p.timezone||'UTC'}):null;b.schedules.push({scenario:s,expression,seconds:Math.max(1,Number(p.seconds)||60),due:expression?expression.next().getTime():Date.now()+Math.max(1,Number(p.seconds)||60)*1000});}
 b.timer=setInterval(async()=>{if(b.ticking||b.status!=='online')return;b.ticking=true;try{const now=Date.now();for(const task of b.schedules)if(task.due<=now){launch(b,task.scenario,{guild:b.project.settings.guildId?{id:b.project.settings.guildId}:undefined});task.due=task.expression?task.expression.next().getTime():now+task.seconds*1000;}
  for(const job of db.prepare('SELECT * FROM jobs WHERE project=? AND due<=? ORDER BY due LIMIT 20').all(b.project.id,now)){try{const p=JSON.parse(job.data);if(job.kind==='giveaway')await finishGiveaway(b.project.id,p.id,b.client);else if(job.kind==='reminder'){const c=await b.client.channels.fetch(p.channel);await c.send({content:p.content,allowedMentions:{parse:[]}});}db.prepare('DELETE FROM jobs WHERE id=?').run(job.id);}catch(e){b.services.error(e);db.prepare('UPDATE jobs SET due=? WHERE id=?').run(now+60000,job.id);}}
 }catch(e){b.services.error(e);}finally{b.ticking=false;}},1000);
}
export function startBot(id,token){
 if(bots.has(id)&&['connecting','online'].includes(bots.get(id).status))throw Error('Бот уже запущен');
 const project=getProject(id),errors=validateProject(project);if(errors.length)throw Error(errors.join('\n'));if(!token)throw Error('Токен не указан');
 const intentNames=project.settings.intents||['Guilds'];const intents=intentNames.map(n=>GatewayIntentBits[n]);if(intents.some(v=>v===undefined))throw Error('Неизвестный Gateway Intent');
 const client=new Client({intents,partials:[Partials.Channel,Partials.Message,Partials.Reaction,Partials.User,Partials.GuildMember],allowedMentions:{parse:[]}});
 const b={project,client,status:'connecting',token,services:null,voiceSessions:new Map()};
 b.services={client,error:e=>{const message=String(e.message||e).replaceAll(token,'[TOKEN]');b.lastError=message;log(id,'error',message);},event:(event,input)=>dispatch(b,event,input)};bots.set(id,b);
 client.on('error',b.services.error);client.on('warn',m=>log(id,'warning',m));client.on('shardReconnecting',()=>{b.status='connecting';});client.on('shardResume',()=>{b.status='online';});client.on('shardDisconnect',event=>{if([4004,4013,4014].includes(event.code)){b.status='error';b.services.error(Error(`Discord Gateway ${event.code}: проверьте токен и разрешённые intents в Developer Portal`));}});
 client.once('clientReady',()=>{if(b.status==='stopping')return;b.status='online';client.user.setPresence({status:project.settings.status||'online',activities:project.settings.activity?[{name:project.settings.activity,type:0}]:[]});try{schedule(b);dispatch(b,'ready',{bot:userData(client.user)});log(id,'info',`Бот ${client.user.tag} подключён к Discord`);}catch(e){b.services.error(e);}});
 client.on('messageCreate',message=>{if(message.author.bot||message.webhookId)return;const input=base(message);dispatch(b,'message_create',input);for(const s of project.scenarios){if(s.enabled===false)continue;const t=trigger(s);if(t?.data.kind!=='trigger.text')continue;const p=t.data.params;const matches=p.command&&(p.match==='equals'?message.content===p.command:p.match==='contains'?message.content.includes(p.command):message.content.startsWith(p.command));if(matches)launch(b,s,{...input,args:{text:message.content.slice(p.command.length).trim(),words:message.content.slice(p.command.length).trim().split(/\s+/)}});}});
 client.on('interactionCreate',async i=>{try{
  const s=project.scenarios.find(s=>{if(s.enabled===false)return false;const t=trigger(s),p=t?.data.params;if(!t)return false;if(i.isAutocomplete())return t.data.kind==='trigger.autocomplete'&&p.name===i.commandName;if(i.isChatInputCommand())return t.data.kind==='trigger.slash'&&p.name===i.commandName;if(i.isContextMenuCommand())return t.data.kind==='trigger.context'&&p.name===i.commandName;if(i.isButton()||i.isAnySelectMenu()||i.isModalSubmit())return t.data.kind==='trigger.component'&&p.customId===i.customId&&p.type===(i.isButton()?'button':i.isModalSubmit()?'modal':'select');return false;});
  if(!s){if(i.isAutocomplete())await i.respond([]);else if(i.isRepliable())await i.reply({content:'Сценарий не найден. Обновите команды в DBK.',flags:64});return;}
  const t=trigger(s);const required=t.data.params.permission;if(required&&!i.memberPermissions?.has(required)){await i.reply({content:'Недостаточно прав для этой команды.',flags:64});return;}
  const first=s.nodes.find(n=>n.id===s.edges.find(e=>e.source===t.id)?.target);const opensModal=first?.data.kind==='component.modal';
  if(!i.isAutocomplete()&&!opensModal)await i.deferReply(t.data.params.ephemeral||first?.data.params.ephemeral?{flags:64}:{});
  const options={};function collect(items){for(const o of items||[]){if(o.options)collect(o.options);else options[o.name]=o.value;}}collect(i.options?.data);
  const fields={};if(i.isModalSubmit())for(const [key,f] of i.fields.fields)fields[key]=f.value??f.values??null;
  const r=launch(b,s,{...base(i),user:userData(i.user),interaction:i,options,customId:i.customId,values:i.values,fields,locale:i.locale,focused:i.isAutocomplete()?i.options.getFocused(true):undefined,targetUser:i.targetUser?userData(i.targetUser):undefined,targetMessage:i.targetMessage?{id:i.targetMessage.id,content:i.targetMessage.content}:undefined});
  if(!r){if(i.isAutocomplete())await i.respond([]);else if(i.deferred)await i.editReply('Бот занят. Повторите команду чуть позже.');else await i.reply({content:'Бот занят.',flags:64});return;}
  await r.promise;
  if(i.isAutocomplete()){if(!i.responded)await i.respond([]);}else if(i.deferred&&!r.ctx.replied)await i.editReply(r.status==='error'?`Не удалось выполнить сценарий. Ошибка записана в DBK.`:'Готово.');
 }catch(e){b.services.error(e);try{if(i.isAutocomplete()){if(!i.responded)await i.respond([]);}else if(i.isRepliable()){if(i.deferred||i.replied)await i.editReply('Ошибка выполнения. Подробности в журнале DBK.');else await i.reply({content:'Ошибка выполнения.',flags:64});}}catch{}}});
 for(const [event,name] of Object.entries(events))client.on(event,(...args)=>{void(async()=>{
  let value=event.endsWith('Update')?args[1]:args[0];if(value?.partial&&value.fetch)try{value=await value.fetch();}catch{}
  const input=base(value);if(name.startsWith('reaction_')){input.user=userData(args[1]);input.emoji=value?.emoji?.id||value?.emoji?.name;}if(name.startsWith('scheduled_event_user_'))input.user=userData(args[1]);
  if(name==='voice_update'){input.user=userData(value.member?.user);input.oldChannelId=args[0].channelId;input.newChannelId=value.channelId;const key=`${value.guild.id}:${value.id}`;let seconds=0;if(args[0].channelId!==value.channelId){const started=b.voiceSessions.get(key);if(started)seconds=Math.floor((Date.now()-started)/1000);if(value.channelId)b.voiceSessions.set(key,Date.now());else b.voiceSessions.delete(key);}input.voice={mute:value.mute,deaf:value.deaf,seconds};}
  if(name==='presence_update'){input.status=value.status;input.activities=value.activities.map(a=>({name:a.name,type:a.type}));}
  if(name==='member_update'){if(args[0].premiumSinceTimestamp!==value.premiumSinceTimestamp&&value.premiumSinceTimestamp)dispatch(b,'boost',input);if(args[0].pending&&!value.pending)dispatch(b,'onboarding_complete',input);}
  dispatch(b,name,input);
 })().catch(b.services.error);});
 client.on('guildAuditLogEntryCreate',(entry,guild)=>{const input={guild:{id:guild.id,name:guild.name},user:{id:entry.targetId},audit:{action:entry.action,executorId:entry.executorId,reason:entry.reason,targetId:entry.targetId}};dispatch(b,'audit_log',input);if(entry.action===AuditLogEvent.MemberKick)dispatch(b,'member_kick',input);});
 client.login(token).catch(e=>{if(b.status!=='stopping'&&b.status!=='offline'){b.status='error';b.services.error(e);client.destroy();}});return botState(id);
}
export async function stopBot(id){const b=bots.get(id);if(!b)return botState(id);b.status='stopping';clearInterval(b.timer);for(const r of runs.values())if(r.project===id)cancelRun(r.id);await cleanup(id);await b.client.destroy();b.token='';b.status='offline';log(id,'info','Бот остановлен');return botState(id);}
export async function deployCommands(id){const b=bots.get(id);if(!b||b.status!=='online')throw Error('Сначала запустите бота');const project=getProject(id);const errors=validateProject(project);if(errors.length)throw Error(errors.join('\n'));const commands=[];
 for(const s of project.scenarios){if(s.enabled===false)continue;const t=trigger(s),p=t?.data.params;if(t?.data.kind==='trigger.slash'){const options=typeof p.options==='string'?JSON.parse(p.options):p.options;commands.push({name:p.name,description:p.description,type:1,options:options||[],default_member_permissions:p.permission?new PermissionsBitField(p.permission).bitfield.toString():undefined});}else if(t?.data.kind==='trigger.context')commands.push({name:p.name,type:p.type==='user'?2:3});}
 const appId=project.settings.applicationId||b.client.user.id;const route=project.settings.guildId?Routes.applicationGuildCommands(appId,project.settings.guildId):Routes.applicationCommands(appId);await new REST({version:'10'}).setToken(b.token).put(route,{body:commands});log(id,'info',`Зарегистрировано команд: ${commands.length}. ${project.settings.guildId?'На тестовом сервере.':'Глобально.'}`);return {count:commands.length};
}
