import { createHash, randomUUID, randomInt } from 'node:crypto';
import { Worker } from 'node:worker_threads';
import { readFile, writeFile, readdir, unlink, mkdir } from 'node:fs/promises';
import { dirname } from 'node:path';
import { safeFile, DatabaseSync } from './utility-db.mjs';
const parsed=x=>{try{return JSON.parse(x);}catch{return x;}};
const blocked=new Set(['__proto__','constructor','prototype']);
export function get(obj,path){return String(path).split('.').reduce((a,k)=>blocked.has(k)?undefined:a?.[k],obj);}
export function transform(p){const v=parsed(p.value),a=parsed(p.argument),e=parsed(p.extra);switch(p.operation){
 case 'length':return v?.length??Object.keys(v||{}).length;case 'trim':return String(v).trim();case 'upper':return String(v).toUpperCase();case 'lower':return String(v).toLowerCase();case 'replace':return String(v).replaceAll(String(a),String(e??''));case 'split':return String(v).split(String(a));case 'join':return v.join(String(a));case 'slice':return v.slice(Number(a)||0,e===''?undefined:Number(e));case 'includes':return v.includes(a);
 case 'add':return Number(v)+Number(a);case 'subtract':return Number(v)-Number(a);case 'multiply':return Number(v)*Number(a);case 'divide':if(!Number(a))throw Error('Деление на ноль');return Number(v)/Number(a);case 'modulo':return Number(v)%Number(a);case 'power':return Number(v)**Number(a);case 'sqrt':return Math.sqrt(Number(v));case 'round':return Math.round(Number(v));case 'floor':return Math.floor(Number(v));case 'ceil':return Math.ceil(Number(v));case 'min':return Math.min(...(Array.isArray(v)?v:[v,a]).map(Number));case 'max':return Math.max(...(Array.isArray(v)?v:[v,a]).map(Number));case 'abs':return Math.abs(Number(v));
 case 'random':return Number(v)+Math.random()*(Number(a)-Number(v));case 'random_item':if(!Array.isArray(v)||!v.length)throw Error('Нужен непустой массив');return v[randomInt(v.length)];case 'shuffle':{const out=[...v];for(let i=out.length-1;i>0;i--){const j=randomInt(i+1);[out[i],out[j]]=[out[j],out[i]];}return out;}
 case 'json_parse':return typeof p.value==='string'?JSON.parse(p.value):v;case 'json_stringify':return JSON.stringify(v);case 'get':return get(v,a);case 'set':case 'delete':{const out=structuredClone(v),keys=String(a).split('.');if(keys.some(k=>blocked.has(k)))throw Error('Недопустимый путь');let ref=out;for(const k of keys.slice(0,-1))ref=ref[k]??(ref[k]={});if(p.operation==='delete')delete ref[keys.at(-1)];else ref[keys.at(-1)]=e;return out;}case 'merge':return {...v,...a};
 case 'now':return new Date().toISOString();case 'date_parse':return new Date(v).getTime();case 'date_format':return new Intl.DateTimeFormat(String(a||'ru-RU'),{dateStyle:'medium',timeStyle:'short',timeZone:String(e||'UTC')}).format(new Date(v));case 'date_add':return new Date(new Date(v).getTime()+Number(a)).toISOString();case 'date_diff':return new Date(v).getTime()-new Date(a).getTime();
 case 'base64_encode':return Buffer.from(String(v)).toString('base64');case 'base64_decode':return Buffer.from(String(v),'base64').toString();case 'url_encode':return encodeURIComponent(String(v));case 'url_decode':return decodeURIComponent(String(v));case 'hex_encode':return Buffer.from(String(v)).toString('hex');case 'hex_decode':return Buffer.from(String(v),'hex').toString();case 'sha256':case 'sha1':case 'md5':return createHash(p.operation).update(String(v)).digest('hex');case 'uuid':return randomUUID();default:throw Error('Неизвестное преобразование');}}
export async function regex(p){if(String(p.value).length>100000)throw Error('Текст больше 100 КБ');return new Promise((resolve,reject)=>{const w=new Worker(`const {parentPort,workerData:p}=require('node:worker_threads');try{const re=new RegExp(p.pattern,p.flags);let r=p.operation==='test'?re.test(p.value):p.operation==='match'?p.value.match(re):p.value.replace(re,p.replacement);parentPort.postMessage({result:r});}catch(e){parentPort.postMessage({error:e.message});}`,{eval:true,workerData:{...p,value:String(p.value)}});const timer=setTimeout(()=>{w.terminate();reject(Error('Regex превысил лимит 500 мс'));},500);w.once('message',r=>{clearTimeout(timer);w.terminate();r.error?reject(Error(r.error)):resolve(r.result);});w.once('error',e=>{clearTimeout(timer);reject(e);});});}
export async function http(p,signal){const url=new URL(p.url);if(!['http:','https:'].includes(url.protocol))throw Error('Только HTTP/HTTPS');const response=await fetch(url,{method:p.method,headers:{'Content-Type':'application/json',...p.headers},body:['GET','HEAD'].includes(p.method)?undefined:JSON.stringify(p.body),signal:AbortSignal.any([signal,AbortSignal.timeout(15000)])});let size=0,chunks=[];for await(const chunk of response.body){size+=chunk.length;if(size>10_000_000)throw Error('HTTP-ответ больше 10 МБ');chunks.push(chunk);}const content=Buffer.concat(chunks).toString();return {status:response.status,ok:response.ok,headers:Object.fromEntries(response.headers),body:parsed(content)};}
export async function file(p,ctx){const path=safeFile(ctx.project.id,p.path);switch(p.operation){case 'read':return readFile(path,'utf8');case 'list':return readdir(path);case 'write':await mkdir(dirname(path),{recursive:true});await writeFile(path,typeof p.value==='string'?p.value:JSON.stringify(p.value));return path;case 'delete':await unlink(path);return true;case 'download':{const url=new URL(p.value);if(!['http:','https:'].includes(url.protocol))throw Error('Только HTTP/HTTPS');const r=await fetch(url,{signal:AbortSignal.any([ctx.run.controller.signal,AbortSignal.timeout(15000)])});if(!r.ok)throw Error(`HTTP ${r.status}`);const chunks=[];let bytes=0;for await(const c of r.body){bytes+=c.length;if(bytes>25_000_000)throw Error('Файл больше 25 МБ');chunks.push(c);}await mkdir(dirname(path),{recursive:true});await writeFile(path,Buffer.concat(chunks));return path;}}}
export function sql(p,ctx){const database=new DatabaseSync(safeFile(ctx.project.id,'data.sqlite'));try{database.exec('CREATE TABLE IF NOT EXISTS records(id TEXT PRIMARY KEY,value TEXT)');const stmt=database.prepare(p.query);return p.mode==='run'?stmt.run(...p.params):stmt.all(...p.params);}finally{database.close();}}
export async function external(p){switch(p.driver){case 'postgres':{const {Client}=await import('pg');const c=new Client({connectionString:p.url,connectionTimeoutMillis:10000,query_timeout:15000});await c.connect();try{return (await c.query(p.query,p.params)).rows;}finally{await c.end();}}case 'mysql':{const {createConnection}=await import('mysql2/promise');const c=await createConnection(p.url);try{return (await c.execute(p.query,p.params))[0];}finally{await c.end();}}case 'redis':{const {createClient}=await import('redis');const c=createClient({url:p.url,socket:{connectTimeout:10000,reconnectStrategy:false}});c.on('error',()=>{});await c.connect();try{return await c.sendCommand([p.query,...p.params.map(String)]);}finally{await c.quit();}}case 'mongodb':{const {MongoClient}=await import('mongodb');const c=new MongoClient(p.url,{serverSelectionTimeoutMS:10000});await c.connect();try{return await c.db().collection(p.query).find(p.params[0]||{}).limit(1000).toArray();}finally{await c.close();}}default:throw Error('Неизвестный драйвер');}}
