import { useState, useMemo, useCallback, memo } from 'react';
import { ReactFlow, ReactFlowProvider, Background, BackgroundVariant, Controls, MiniMap, Handle, Position, useReactFlow, type NodeProps } from '@xyflow/react';
import { MagnifyingGlass, Plus, X, ArrowRight, Trash, Copy, PauseCircle, CaretDown, DotsSixVertical, Info, SquaresFour, Check, ArrowSquareOut } from '@phosphor-icons/react';
import { byId, groups, catalog } from '../runtime/catalog.mjs';
import { useEditor } from './store';
import { GroupIcon, Empty } from './components';
import type { BlockNode, Field, Run } from './types';
const portNames:Record<string,string>={next:'Далее',true:'Да',false:'Нет',body:'Повторять',done:'Готово',catch:'Ошибка'};
const nodeTypes={block:memo(function Block({data,id,selected}:NodeProps<BlockNode>){
 const def=byId[data.kind];const select=useEditor(s=>s.select);if(!def)return <div className="flow-node invalid">Неизвестный блок: {data.kind}</div>;
 const summary=String(data.params.content||data.params.name||data.params.event||data.params.message||data.params.key||data.params.action||data.params.scenario||data.params.text||def.description);
 return <div className={`flow-node ${selected?'selected':''} category-${def.group}`} onDoubleClick={()=>select(id)}>
  {!data.kind.startsWith('trigger.')&&<Handle type="target" position={Position.Left}/>}
  <div className="node-head"><span className="node-icon"><GroupIcon group={def.group} size={18}/></span><span>{data.label||def.title}</span>{data.breakpoint&&<PauseCircle size={15} weight="fill" className="breakpoint"/>}<DotsSixVertical size={17} className="muted"/></div>
  <div className="node-description">{summary.length>105?summary.slice(0,105)+'…':summary}</div>
  <div className="node-bottom"><code>{data.kind}</code><span>{def.ports.length===1?'Далее':def.ports.length?'Ветвление':'Конец'}</span></div>
  {def.ports.map((port,i)=><Handle key={port} id={port} type="source" position={Position.Right} style={{top:`${((i+1)/(def.ports.length+1))*100}%`}} title={portNames[port]}><span className={`port-label ${port}`}>{def.ports.length>1?portNames[port]:''}</span></Handle>)}
 </div>;
})};
function FieldInput({field,value,onChange,scenarioId}:{field:Field;value:unknown;onChange:(v:unknown)=>void;scenarioId:string}){
 const project=useEditor(s=>s.project);const [error,setError]=useState('');
 if(field.key==='scenario')return <select value={String(value||'')} onChange={e=>onChange(e.target.value)}><option value="">Выберите сценарий</option>{project?.scenarios.filter(s=>s.id!==scenarioId).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select>;
 if(field.type==='boolean')return <button className={`toggle ${value?'on':''}`} role="switch" aria-checked={Boolean(value)} aria-label={field.label} onClick={()=>onChange(!value)}><span/></button>;
 if(field.type==='select')return <select value={String(value??'')} onChange={e=>onChange(e.target.value)}>{field.options?.map(o=><option value={o} key={o}>{o}</option>)}</select>;
 if(field.type==='json'||field.type==='textarea')return <><textarea spellCheck={false} className={field.type==='json'?'code-input':''} rows={field.type==='json'?5:3} value={typeof value==='string'?value:JSON.stringify(value,null,2)} onChange={e=>{onChange(e.target.value);if(field.type==='json'){try{JSON.parse(e.target.value);setError('');}catch{setError('Проверьте JSON или используйте {{переменную}}');}}}/>{error&&<small className="field-warning">{error}</small>}</>;
 return <input type={field.type==='number'?'number':'text'} value={String(value??'')} onChange={e=>onChange(field.type==='number'?Number(e.target.value):e.target.value)} spellCheck={false}/>;
}
function OptionBuilder({value,onChange}:{value:unknown;onChange:(v:string)=>void}){
 let options:Record<string,unknown>[];try{options=typeof value==='string'?JSON.parse(value):value as Record<string,unknown>[];if(!Array.isArray(options))return null;}catch{return null;}
 const update=(index:number,patch:Record<string,unknown>)=>onChange(JSON.stringify(options.map((o,i)=>i===index?{...o,...patch}:o),null,2));
 return <div className="option-builder"><div className="section-caption">Опции команды<button className="icon small" title="Добавить опцию" onClick={()=>onChange(JSON.stringify([...options,{name:'option'+(options.length+1),description:'Описание опции',type:3,required:false}],null,2))}><Plus size={16}/></button></div>{options.map((o,i)=><div className="option-row" key={i}><div className="inline"><input aria-label="Имя опции" value={String(o.name||'')} onChange={e=>update(i,{name:e.target.value})}/><button className="icon" aria-label="Удалить опцию" onClick={()=>onChange(JSON.stringify(options.filter((_,j)=>i!==j),null,2))}><X size={14}/></button></div><input aria-label="Описание опции" value={String(o.description||'')} onChange={e=>update(i,{description:e.target.value})}/><select aria-label="Тип опции" value={Number(o.type)} onChange={e=>update(i,{type:Number(e.target.value)})}>{[[3,'Текст'],[4,'Целое число'],[10,'Число'],[5,'Да / нет'],[6,'Пользователь'],[7,'Канал'],[8,'Роль'],[11,'Вложение']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><label className="check-row"><input type="checkbox" checked={Boolean(o.required)} onChange={e=>update(i,{required:e.target.checked})}/>Обязательная</label><label className="check-row"><input type="checkbox" checked={Boolean(o.autocomplete)} onChange={e=>update(i,{autocomplete:e.target.checked})}/>Автокомплит</label></div>)}</div>;
}
function MessageBuilder({params,onChange}:{params:Record<string,unknown>;onChange:(p:Record<string,unknown>)=>void}){
 let components:Record<string,any>[]=[],embeds:Record<string,any>[]=[];try{components=JSON.parse(String(params.components||'[]'));embeds=JSON.parse(String(params.embeds||'[]'));}catch{return null;}
 const buttons=components.flatMap((r,ri)=>(r.components||[]).filter((c:any)=>c.type===2).map((c:any)=>({...c,ri})));const embed=embeds[0];
 return <div className="message-builder"><div className="section-caption">Быстро добавить</div><div className="preset-buttons"><button onClick={()=>onChange({embeds:JSON.stringify([{title:'Заголовок',description:'Описание сообщения',color:10544309}])})}>Embed</button><button onClick={()=>{const all=structuredClone(components);let row=all.find(r=>r.type===1&&r.components?.every((c:any)=>c.type===2)&&r.components.length<5);if(!row){if(all.length>=5)return;row={type:1,components:[]};all.push(row);}row.components.push({type:2,style:1,label:'Кнопка',custom_id:'button:'+crypto.randomUUID().slice(0,8)});onChange({components:JSON.stringify(all,null,2)});}}>Кнопка</button><button onClick={()=>{if(components.length>=5)return;onChange({components:JSON.stringify([...components,{type:1,components:[{type:3,custom_id:'menu',placeholder:'Выберите вариант',options:[{label:'Первый вариант',value:'first'}]}]}],null,2)});}}>Меню</button><button onClick={()=>onChange({poll:JSON.stringify({question:{text:'Какой вариант выбираем?'},answers:[{text:'Первый'},{text:'Второй'}],duration:24,allowMultiselect:false},null,2)})}>Опрос</button></div>
 {embed&&<div className="option-row"><div className="section-caption">Embed<button className="icon small" aria-label="Удалить embed" onClick={()=>onChange({embeds:'[]'})}><X size={13}/></button></div><input aria-label="Заголовок embed" value={embed.title||''} onChange={e=>onChange({embeds:JSON.stringify([{...embed,title:e.target.value},...embeds.slice(1)])})}/><textarea aria-label="Описание embed" value={embed.description||''} onChange={e=>onChange({embeds:JSON.stringify([{...embed,description:e.target.value},...embeds.slice(1)])})}/><label className="inline">Цвет<input type="color" value={'#'+Number(embed.color||0).toString(16).padStart(6,'0')} onChange={e=>onChange({embeds:JSON.stringify([{...embed,color:parseInt(e.target.value.slice(1),16)},...embeds.slice(1)])})}/></label></div>}
 {buttons.map((b,i)=><div className="option-row" key={i}><div className="section-caption">Кнопка {i+1}</div><input aria-label="Текст кнопки" value={b.label} onChange={e=>{const all=structuredClone(components);all[b.ri].components.find((c:any)=>(c.custom_id||c.url)===(b.custom_id||b.url)).label=e.target.value;onChange({components:JSON.stringify(all,null,2)});}}/><input aria-label="Custom ID или URL" value={b.custom_id||b.url||''} onChange={e=>{const all=structuredClone(components);const c=all[b.ri].components.find((c:any)=>(c.custom_id||c.url)===(b.custom_id||b.url));c[b.style===5?'url':'custom_id']=e.target.value;onChange({components:JSON.stringify(all,null,2)});}}/><select aria-label="Стиль кнопки" value={b.style} onChange={e=>{const all=structuredClone(components);const c=all[b.ri].components.find((c:any)=>(c.custom_id||c.url)===(b.custom_id||b.url));c.style=Number(e.target.value);if(c.style===5){c.url='https://example.com';delete c.custom_id;}else{c.custom_id=c.custom_id||'button';delete c.url;}onChange({components:JSON.stringify(all,null,2)});}}>{[[1,'Основная'],[2,'Вторичная'],[3,'Успех'],[4,'Опасность'],[5,'Ссылка']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><button className="text-button danger-text" onClick={()=>{const all=structuredClone(components);all[b.ri].components=all[b.ri].components.filter((c:any)=>(c.custom_id||c.url)!==(b.custom_id||b.url));onChange({components:JSON.stringify(all.filter(r=>r.components.length),null,2)});}}>Удалить кнопку</button></div>)}
 </div>;
}
function Inspector(){const {project,scenarioId,selected,select,updateNode,renameNode,removeNode,toggleBreakpoint,copy,paste}=useEditor();const scenario=project?.scenarios.find(s=>s.id===scenarioId);const node=scenario?.nodes.find(n=>n.id===selected);const [advanced,setAdvanced]=useState(false);
 if(!node)return <aside className="inspector"><div className="panel-heading">Инспектор</div><div className="inspector-empty"><span className="large-outline"><ArrowSquareOut size={30}/></span><h3>Всё начинается с блока</h3><p>Выберите блок на холсте, чтобы настроить его поведение.</p><div className="shortcut-list"><span>Сохранить<kbd>Ctrl S</kbd></span><span>Отменить<kbd>Ctrl Z</kbd></span><span>Дублировать<kbd>Ctrl D</kbd></span><span>Выбрать несколько<kbd>Shift</kbd></span></div><div className="tip"><Info size={17}/><p>Перетащите связь от выхода одного блока ко входу другого.</p></div></div></aside>;
 if(node.type==='group')return <aside className="inspector"><div className="panel-heading">Группа<button className="icon" onClick={()=>select(null)}><X/></button></div><div className="inspector-body"><label className="field">Название<input value={node.data.label||''} onChange={e=>renameNode(node.id,e.target.value)}/></label><button onClick={()=>removeNode(node.id)}>Разгруппировать</button></div></aside>;
 const def=byId[node.data.kind];if(!def)return null;
 const advancedKeys=node.data.kind==='message.send'?['embeds','components','files','poll']:node.data.kind==='trigger.slash'?['options']:[];
 return <aside className="inspector" key={node.id}><div className="panel-heading"><span>Настройки блока</span><button className="icon" aria-label="Закрыть инспектор" onClick={()=>select(null)}><X size={17}/></button></div><div className="inspector-body"><div className="inspector-title"><span className="node-icon"><GroupIcon group={def.group} size={23}/></span><div><h3>{def.title}</h3><code>{def.id}</code></div></div><p className="block-description">{def.description}</p><label className="field">Название на холсте<input placeholder={def.title} value={node.data.label||''} onChange={e=>renameNode(node.id,e.target.value)}/></label>
 {def.fields.filter(f=>!advancedKeys.includes(f.key)).map(f=><label key={f.key} className={`field ${f.type==='boolean'?'boolean-field':''}`}><span>{f.label}</span><FieldInput field={f} value={node.data.params[f.key]??f.default} scenarioId={scenarioId} onChange={v=>updateNode(node.id,{[f.key]:v})}/></label>)}
 {node.data.kind==='trigger.slash'&&<OptionBuilder value={node.data.params.options} onChange={value=>updateNode(node.id,{options:value})}/>}
 {node.data.kind==='message.send'&&<MessageBuilder params={node.data.params} onChange={p=>updateNode(node.id,p)}/>}
 {advancedKeys.length>0&&<><button className="advanced-toggle" onClick={()=>setAdvanced(!advanced)}><CaretDown size={14} style={{transform:advanced?'rotate(180deg)':''}}/>Расширенные параметры JSON</button>{advanced&&def.fields.filter(f=>advancedKeys.includes(f.key)).map(f=><label className="field" key={f.key}>{f.label}<FieldInput field={f} value={node.data.params[f.key]??f.default} scenarioId={scenarioId} onChange={v=>updateNode(node.id,{[f.key]:v})}/></label>)}</>}
 <div className="variable-hint"><span>Переменные в тексте</span><code>{'{{user.username}}'}</code><code>{'{{options.name}}'}</code><code>{'{{temp.result}}'}</code><code>{'{{global.name}}'}</code></div><div className="inspector-actions"><button onClick={()=>{copy();paste();}}><Copy size={15}/>Дублировать</button><button className={node.data.breakpoint?'active':''} onClick={()=>toggleBreakpoint(node.id)} title="Приостанавливает настоящий запуск на этом блоке"><PauseCircle size={15}/>Пауза</button><button className="icon danger-text" aria-label="Удалить блок" onClick={()=>removeNode(node.id)}><Trash size={16}/></button></div></div></aside>;
}
function Library(){const [search,setSearch]=useState(''),[expanded,setExpanded]=useState<string[]>(['triggers','messages']);const addNode=useEditor(s=>s.addNode);const {screenToFlowPosition}=useReactFlow();return <aside className="library"><div className="panel-heading">Блоки<span className="count">{catalog.length}</span></div><div className="search"><MagnifyingGlass size={17}/><input placeholder="Найти блок…" aria-label="Поиск блоков" value={search} onChange={e=>setSearch(e.target.value)}/><kbd>/</kbd></div><div className="library-groups">{groups.map(g=>{const items=g.items.filter(n=>`${n.title} ${n.description} ${n.id}`.toLowerCase().includes(search.toLowerCase()));if(!items.length)return null;const open=search||expanded.includes(g.id);return <section key={g.id}><button className={`group-heading ${open?'open':''}`} onClick={()=>setExpanded(expanded.includes(g.id)?expanded.filter(id=>id!==g.id):[...expanded,g.id])}><GroupIcon group={g.id} size={17}/><span>{g.title}</span><CaretDown size={12}/></button>{open&&<div className="group-items">{items.map(n=><button key={n.id} className="library-item" draggable title={n.description} onDragStart={e=>{e.dataTransfer.setData('application/dbk-node',n.id);e.dataTransfer.effectAllowed='move';}} onClick={()=>{const el=document.querySelector('.react-flow');const r=el?.getBoundingClientRect();addNode(n.id,r?screenToFlowPosition({x:r.left+r.width/2-140,y:r.top+r.height/2-60}):undefined);}}><span>{n.title}</span><Plus size={13}/></button>)}</div>}</section>;})}{!groups.some(g=>g.items.some(n=>`${n.title} ${n.description} ${n.id}`.toLowerCase().includes(search.toLowerCase())))&&<p className="no-results">Ничего не найдено</p>}</div><div className="library-footer"><span className="status-dot"/>Все блоки бесплатны</div></aside>;}
function Canvas({runs}:{runs:Run[]}){const {project,scenarioId,changeNodes,changeEdges,connect,select,addNode,checkpoint,group}=useEditor();const scenario=project?.scenarios.find(s=>s.id===scenarioId);const {screenToFlowPosition}=useReactFlow();const active=runs.find(r=>r.scenario===scenarioId&&['running','paused'].includes(r.status));const nodes=useMemo(()=>scenario?.nodes.map(n=>({...n,className:active?.active===n.id?'executing':''}))||[],[scenario?.nodes,active?.active]);const drop=useCallback((e:React.DragEvent)=>{e.preventDefault();const kind=e.dataTransfer.getData('application/dbk-node');if(byId[kind])addNode(kind,screenToFlowPosition({x:e.clientX,y:e.clientY}));},[addNode,screenToFlowPosition]);
 if(!scenario)return <Empty title="Добавьте сценарий" text="Каждый сценарий хранит отдельную логику вашего бота."/>;
 return <div className="canvas-wrap"><ReactFlow key={scenarioId} nodes={nodes} edges={scenario.edges} nodeTypes={nodeTypes} onNodesChange={changeNodes} onEdgesChange={changeEdges} onConnect={connect} onNodeClick={(_,n)=>select(n.id)} onPaneClick={()=>select(null)} onNodeDragStart={checkpoint} onDrop={drop} onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect='move';}} fitView fitViewOptions={{padding:.35,maxZoom:1}} minZoom={.2} maxZoom={1.8} deleteKeyCode={['Backspace','Delete']} selectionKeyCode="Shift" panOnScroll selectionOnDrag panOnDrag={[1,2]} defaultEdgeOptions={{type:'smoothstep',style:{stroke:'var(--edge)',strokeWidth:1.7}} proOptions={{hideAttribution:false}}><Background variant={BackgroundVariant.Dots} gap={22} size={1} color="var(--dot)"/><Controls showInteractive={false}/><MiniMap pannable zoomable nodeColor="var(--minimap-node)" maskColor="var(--minimap-mask)"/></ReactFlow><div className="canvas-label"><span className="status-dot"/><span>{scenario.name}</span><span className="canvas-label-divider"/>{scenario.nodes.filter(n=>n.type!=='group').length} блоков</div><button className="group-selection" title="Сгруппировать выбранные блоки" onClick={group}><SquaresFour size={16}/>Группа</button>{active&&<div className="run-indicator"><span className="status-dot pulse"/>{active.status==='paused'?'Выполнение на паузе':'Сценарий выполняется'}</div>}</div>;
}
export function Editor({runs}:{runs:Run[]}){return <ReactFlowProvider><div className="editor"><Library/><Canvas runs={runs}/><Inspector/></div></ReactFlowProvider>;}
